version: '3'

vars:
  PATH1: ~/.nix-profile/bin:/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin
  PATH2: /usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin

tasks:
  run:
    desc: run all
    cmds:
      - task: run:py
      - task: run:sh
      - task: run:c
  bench:
    desc: benchmark all
    cmds:
      - task: bench:py
      - task: bench:sh
      - task: bench:c
  diff:
    desc: diff the outputs
    cmds:
      - difft py.out sh.out
      - difft py.out c.out
      - difft sh.out c.out
  run:py:
    desc: Run the Python script
    cmds:
      - src/diffpath.py {{.PATH1}} {{.PATH2}} > py.out
  bench:py:
    desc: Run the benchmark for Python
    cmds:
      - hyperfine --warmup 3 'src/diffpath.py {{.PATH1}} {{.PATH2}}'
  run:sh:
    desc: Run the bash script
    cmds:
      - src/diffpath.sh {{.PATH1}} {{.PATH2}} > sh.out
  bench:sh:
    desc: Run the benchmark for bash
    cmds:
      - hyperfine --warmup 3 'src/diffpath.sh {{.PATH1}} {{.PATH2}}'
  run:c:
    desc: Run the C program
    cmds:
      - bin/diffpath_c {{.PATH1}} {{.PATH2}} > c.out
  bench:c:
    desc: Run the benchmark for C
    cmds:
      - hyperfine --warmup 3 'bin/diffpath_c {{.PATH1}} {{.PATH2}}'
  clean:
    desc: Clean the outputs
    cmds:
      - rm -f *.out
      - make clean
