version: 2.1

executors:
  linux-64:
    machine:
      image: ubuntu-2404:current
    resource_class: medium
  linux-aarch64:
    machine:
      image: ubuntu-2404:current
    resource_class: arm.medium

jobs:
  build-and-test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - restore_cache:
          keys:
            - nix-store-{{ arch }}-{{ checksum "devbox.lock" }}

      - run:
          name: Install Devbox
          command: |
            curl -fsSLO https://get.jetify.com/devbox
            chmod +x devbox
            ./devbox -f

      - run:
          name: Remove default cargo from image
          command: |
            ls $HOME/.cargo
            rm -rf $HOME/.cargo

      - run:
          name: Compilers version
          command: devbox run --config envs/system 'cd ../..; make compiler_version'

      - run:
          name: Compile, run, and test
          command: devbox run --config envs/system 'cd ../..; make all ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='

      - run:
          name: Show size and list dynamically linked libraries
          command: devbox run --config envs/system 'cd ../..; make size list_link -j1'

      - run:
          name: Benchmark
          command: devbox run --config envs/system 'cd ../..; make bench_md ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='

      - save_cache:
          paths:
            - /nix
          key: nix-store-{{ arch }}-{{ checksum "devbox.lock" }}

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              os: [linux-64, linux-aarch64]
