[project]
name = "cython"
channels = ["conda-forge"]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-64",
    "osx-arm64",
]

[dependencies]
autoflake = "*"
black = "*"
python = "*"
isort = "*"
