name: CI

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-13
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Compilers version
        run: devbox run --config envs/system 'cd ../..; make compiler_version'

      - name: compile, run, and test
        run: devbox run --config envs/system 'cd ../..; make all PATH2="$PATH"'

      - name: show size and list dynamically linked libraries
        run: devbox run --config envs/system 'cd ../..; make size list_link -j1'
        
      - name: Benchmark
        run: devbox run --config envs/system 'cd ../..; make bench_md PATH2="$PATH"'
