name: CI

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-13
          - macos-14
        python_method:
          - devbox
          - pixi
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_METHOD: ${{ matrix.python_method }}
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true
      - name: Install Pixi
        if: matrix.python_method == 'pixi'
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          # separated by spaces
          environments: >-
            cython
            nuitka
            python

      - name: Compilers version
        run: devbox run --config envs/system 'cd ../..; make compiler_version'

      - name: compile, run, and test
        run: devbox run --config envs/system 'cd ../..; make all ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='

      - name: show size and list dynamically linked libraries
        run: devbox run --config envs/system 'cd ../..; make size list_link -j1'
        
      - name: Benchmark
        run: devbox run --config envs/system 'cd ../..; make bench_md ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='
